# Site settings
title: Talk.CSS
email: singaporecss@outlook.com
description: The first CSS-centric meetup in Singapore. For anyone who's interested in wrapping their heads around this easy to pick up but hard to master aspect of web development.
baseurl: ""
url: "http://localhost:2610" 

relative_permalinks: false
permalink: /:title/

github_username: SingaporeCSS
twitter_username: SingaporeCSS

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Exclude files and folder
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - yarn.lock

include: ["_pages"]

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
